export const BASE_URL = process.env.BASE_URL ? process.env.BASE_URL : 'http://localhost:3000';

export const CATEGORIES = [
    'Productivity',
    'Developer Tools',
    'Tech',
    'Artifical Intelligence',
    'Marketing',
    'User Experience',
    'Design Tools',
    'Icons',
    'Illustrations',
    'Figma',
    'Notion',
    'Gumroad',
    'Investing',
    'SAAS',
    'Social Media',
    'Open Source',
    'Analytics',
    'Extensions',
    'Mobile Apps',
    'Games',
    'Books',
    'APIs',
    'Video Streaming',
    'Music',
    'Health & Fitness',
    'Other',
  ];